spring:
  application:
    name: history-service

server:
  port: ${PORT:8080}

ai:
  service:
    url: ${AI_BASE_URL:https://vietnamhistorydataset-production.up.railway.app}

logging:
  level:
    root: INFO
    org.springframework.web.reactive.function.client.WebClient: DEBUG
